config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum:3, maximum:50}
  validates :description, presence:true, length: {minimum:10, maximum:200}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  before_save {self.email= email.downcase}

  validates :username, presence:true,
            uniqueness: {case_sensitive: false},
            length:{ minimum: 3,maximum: 25}
  Valid_Email_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: {case_sensitive: false},
            format: {with: Valid_Email_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
      if @article.save
        flash[:success] = 'Article was successfully created.'
        redirect_to @article
      else
        render :new
      end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
      if @article.update(article_params)
        flash[:success] = 'Article was successfully updated.'
        redirect_to @article
      else
        render :edit
      end
    end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
      @article.destroy
      flash[:danger]= 'Article was successfully destroyed.'
      redirect_to articles_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
 <div class="row">
    <div class="col-xs-12'">
      <%= form_for(@article,:html =>{class: 'form',role: "form"}) do |form| %>
        <%= render 'shared/errors', obj: @article %>

        <div class="form-group row">

            <div class="col-xl-2 col-form-label">
              <%= form.label :title %>
            </div>
            <div class="col-xl-10">
              <%= form.text_field :title ,class: "form-control",placeholder: "Title of article", autofocus:true%>
            </div>

        </div>
        <div class="form-group row">

            <div class="col-sm-3 col-form-label">
              <%= form.label :description %>
            </div>
            <div class="col-sm-9">
              <%= form.text_area :description, rows:5 ,class: "form-control",placeholder: "Description of article"%>
            </div>

        </div>
        <div class="form-group row">
          <div class="col-sm-offset-4 col-sm-10">

              <%= form.submit class:"btn btn-primary"%>

          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>Create New Article</h1><br>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2><br>Showing Article</h2>
<p class="h5">
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<br>
<p class="h5">
  <strong>Description:</strong>
  <%= @article.description %>
</p>
<br>
<p class="h5">
  <strong>Created by: </strong>
  <small>
    <%= @article.user.username %>
    <p class="h5">Created at: <%= time_ago_in_words(@article.created_at) %> ago</p>
    <p class="h5">Updated at: <%= time_ago_in_words(@article.updated_at) %> ago</p>
  </small>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy <a href="#">Aplha Blogs</a> by <a href="#">Ahmad Ali</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to 'about',welcome_about_url %>
        </li>
        <li>
          <%= link_to 'contact',"#" %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg color-class">
  <%= link_to 'Alpha Blog',root_path,class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav" >
      <li class="nav-item active">
        <%= link_to 'Articles',articles_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%=link_to "New Articles",new_article_path ,class: "dropdown-item"%>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/welcome/about.html.erb
<h1>About page</h1>
<%= link_to 'home',root_url %>

app/views/welcome/home.html.erb
<div class="jumbotron center">
  <h1 class="display-4">Alpha Blog</h1>
  <hr class="my-4">
  <%= link_to 'Sign up Now',"#",class: "btn btn-danger btn-lg", id:'sign-in' %>
</div>